export enum Key {
  A = "KeyA",
  B = "KeyB",
  C = "KeyC",
  D = "KeyD",
  E = "KeyE",
  F = "KeyF",
  G = "KeyG",
  H = "KeyH",
  I = "KeyI",
  J = "KeyJ",
  K = "KeyK",
  L = "KeyL",
  M = "KeyM",
  N = "KeyN",
  O = "KeyO",
  P = "KeyP",
  Q = "KeyQ",
  R = "KeyR",
  S = "KeyS",
  T = "KeyT",
  U = "KeyU",
  V = "KeyV",
  W = "KeyW",
  X = "KeyX",
  Y = "KeyY",
  Z = "KeyZ",

  Num0 = "Digit0",
  Num1 = "Digit1",
  Num2 = "Digit2",
  Num3 = "Digit3",
  Num4 = "Digit4",
  Num5 = "Digit5",
  Num6 = "Digit6",
  Num7 = "Digit7",
  Num8 = "Digit8",
  Num9 = "Digit9",

  ArrowUp = "ArrowUp",
  ArrowDown = "ArrowDown",
  ArrowLeft = "ArrowLeft",
  ArrowRight = "ArrowRight",

  Space = "Space",
  Enter = "Enter",
  Escape = "Escape",
  Shift = "ShiftLeft",
  Ctrl = "ControlLeft",
  Alt = "AltLeft",
  Tab = "Tab",

  MouseLeft = "__MOUSE_LEFT__",
  MouseRight = "__MOUSE_RIGHT__",
}
